### ISSUE TITLE
No GitHub release

### ISSUE THREAD

**Issue by Kallinteris-Andreas** [RoxanneSHS/Solaufein#2]
https://github.com/RoxanneSHS/Solaufein/releases is empty

**Comment by RoxanneSHS** [comment]
So what is the issue?
You can either download the master (https://github.com/RoxanneSHS/Solaufein, click on green CODE button and select download zip) or use the version of the EE Mod Install Tool (https://www.dropbox.com/s/3hgognru18oo5l5/WSolaufein.zip?dl=1).

There is no named release here but version is 2.05

**Comment by Kallinteris-Andreas** [comment]
It is just a lot easier to manage mod installs if they have GitHub releases (and check for updates)
